// src/main/ui/src/components/Home/Home.vue
<template>
  <div class="container p-3">
    <div class="row">
      <div class="col-sm-2">
        <form class="form-inline">
          <div class="form-group">
            <label for="viewByOptions">View</label>
            <select class="form-control" id="viewByOptions" 
              @change="filterResults($event.target.value)" v-model="viewBy">
              <option value="ALL">All</option>
              <option value="AVAILABLE">Available</option>
              <option value="ON_HIRE">On Hire</option>
            </select>
          </div>
        </form>
      </div>
      <div class="col-sm-2">
        <button class="btn btn-xs btn-primary" @click="getVehicles">Refresh</button>
      </div>
    </div>
    <div class="row p-2" v-if="filteredResults">
      <div class="col-sm-3 p-2" v-for="vehicle in filteredResults" :key="vehicle.id">
        <Vehicle v-bind:vehicle="vehicle"/>
      </div>
    </div>
  </div>
</template>
<script>
  import axios from 'axios';
  import Vehicle from '@/components/Vehicle/Vehicle.vue';
  import getHireStatus from '@/utils/utils.js';

  export default {
    name: 'Vehicles',
    components: { Vehicle },
    data() {
      return {
        VIEW_ALL: "ALL",
        VIEW_HIRED: "ON_HIRE",
        VIEW_AVAILABLE: "AVAILABLE",
        viewBy: 'AVAILABLE',
        vehicles: null,
        filteredResults: null
      };
    },
    created: function() {
      this.getVehicles();
    },
    inject: ['app'],
    methods:{
      async getVehicles() {
        this.setLoading(true);
        try{
           const response = await axios.get("/api/v1/vehicle?showHired=true");
           this.vehicles = await response.data;
           this.filterResults(this.viewBy);
        } catch(err){
          this.setHasError(true);
        } finally {
          this.setLoading(false);
        }
      },
      setLoading(isLoading) {
        this.app.isLoading = isLoading;
      },
      setHasError(hasError) {
        this.app.hasError = hasError;
      },
      setFilteredResults(results){
        this.filteredResults = results;
      },
      filterResults(value){
        if (value === this.VIEW_ALL) {
          this.setFilteredResults(this.vehicles);
        } else if (value === this.VIEW_AVAILABLE) {
          const available = this.vehicles.filter((vehicle) => this.getHireStatus(vehicle));
          this.setFilteredResults(available);
        } else if (value === this.VIEW_HIRED) {
          const onHire = this.vehicles.filter((vehicle) => this.getHireStatus(vehicle, true));
          this.setFilteredResults(onHire);
        }
      },    
      getHireStatus(vehicle, available) {
        return getHireStatus(vehicle, available);
      }
    }
  }
</script>
<style>
  label[for="viewByOptions"] { 
    padding-right:20px
  }
</style>

// src/main/ui/src/components/Home/index.jsx
import { useEffect, useState } from "react";
import axios from "axios";
import { makeStyles } from "@material-ui/core/styles";
import {
  Grid,
  InputLabel,
  Select,
  MenuItem,
  FormControl,
  Button,
} from "@material-ui/core";

import Progress from "../Progress";
import Error from "../Error";
import VehicleCard from "../Vehicle";

const useStyles = makeStyles((theme) => ({
  root: {
    marginTop: theme.spacing(2),
    marginBottom: theme.spacing(2),
  },
}));

const Home = () => {
  const classes = useStyles();
  const [isLoading, setLoading] = useState(false);
  const [hasError, setHasError] = useState(false);
  const [vehicles, setVehicles] = useState([]);

  const VIEW_ALL = "ALL";
  const VIEW_HIRED = "ON_HIRE";
  const VIEW_AVAILABLE = "AVAILABLE";
  const DEFAULT_VIEW = VIEW_AVAILABLE;
  const [view, setView] = useState(DEFAULT_VIEW);
  const [filteredResults, setFilteredResults] = useState([]);

  const getVehicles = async () => {
    setLoading(true);
    try {
      const response = await axios.get("/api/v1/vehicle?showHired=true");
      const data = await response.data;
      setVehicles(data);

      const available = data.filter((vehicle) => getHireStatus(vehicle));
      setFilteredResults(available);
    } catch (error) {
      setHasError(true);
    } finally {
      setLoading(false);
    }
  };
  useEffect(() => {
    getVehicles();
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const getHireStatus = (vehicle, available) => {
    const status = vehicle.hireStatus;
    const hasCustomer = status.customer !== null;
    const hasStartDate = status.startDate !== null;
    const hasEndDate = status.endDate !== null;

    if (available) {
      return hasCustomer && hasStartDate && hasEndDate;
    }
    return !hasCustomer && !hasStartDate && !hasEndDate;
  };

  const handleViewChange = (event) => {
    const value = event.target.value;
    setView(value);

    if (value === VIEW_ALL) {
      setFilteredResults(vehicles);
    } else if (value === VIEW_AVAILABLE) {
      const available = vehicles.filter((vehicle) => getHireStatus(vehicle));
      setFilteredResults(available);
    } else if (value === VIEW_HIRED) {
      const onHire = vehicles.filter((vehicle) => getHireStatus(vehicle, true));
      setFilteredResults(onHire);
    }
  };

  return (
    <Grid item xs={12} sm={10} className={classes.root}>
      {isLoading && <Progress />}
      {hasError && <Error errorMessage="Something went wrong :-(" />}
      {filteredResults.length && (
        <>
          <Grid container spacing={4} alignItems="center">
            <Grid item>
              <FormControl>
                <InputLabel id="view-select-label">View</InputLabel>
                <Select value={view} onChange={handleViewChange}>
                  <MenuItem value={VIEW_ALL}>All</MenuItem>
                  <MenuItem value={VIEW_AVAILABLE}>Available</MenuItem>
                  <MenuItem value={VIEW_HIRED}>On Hire</MenuItem>
                </Select>
              </FormControl>
            </Grid>
            <Grid item>
              <Button variant="contained" color="primary" onClick={getVehicles}>
                Refresh
              </Button>
            </Grid>
          </Grid>
          <Grid container spacing={2}>
            {filteredResults.map((vehicle) => (
              <Grid item xs={12} sm={3} key={vehicle.id}>
                <VehicleCard vehicle={vehicle} />
              </Grid>
            ))}
          </Grid>
        </>
      )}
    </Grid>
  );
};

export default Home;
